sudo: required
services:
    - docker
    
before_install:
    - docker build -t george/docker-react -f Dockerfile.dev .
script:
    - docker run george/docker-react npm run test -- --coverage
deploy:
    provide: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-803441141666"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
        